-- StayEase Hotel Reservation System - Oracle schema
-- Safe to re-run: drops the old tables first (ignores "table does not exist" errors).
-- WARNING: re-running deletes all existing reservations.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE reserved_rooms CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reservations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE app_users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE rooms CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Rooms: inventory, nightly price (INR) and how many guests fit.
--    A room's availability is worked out from reservations by date, so there is no is_available flag.
CREATE TABLE rooms (
    room_number VARCHAR2(10) PRIMARY KEY,
    room_type   VARCHAR2(50) NOT NULL,
    price       NUMBER(10, 2) NOT NULL CHECK (price > 0),
    max_guests  NUMBER(2) NOT NULL CHECK (max_guests BETWEEN 1 AND 3)
);

-- 2. Reservations: one row per booking.
--    status: BOOKED (active), CHECKED_OUT (stay finished), CANCELLED (kept for history).
CREATE TABLE app_users (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(30) UNIQUE NOT NULL,
    password_hash VARCHAR2(64) NOT NULL,
    salt          VARCHAR2(32) NOT NULL,
    full_name     VARCHAR2(100) NOT NULL,
    phone         VARCHAR2(15) NOT NULL,
    email         VARCHAR2(100),
    role          VARCHAR2(10) NOT NULL CHECK (role IN ('ADMIN', 'CUSTOMER')),
    created_at    DATE DEFAULT SYSDATE
);

CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name  VARCHAR2(200) NOT NULL,
    contact_number VARCHAR2(15) NOT NULL,
    check_in_date  DATE NOT NULL,
    check_out_date DATE NOT NULL,
    subtotal       NUMBER(10, 2) NOT NULL,   -- nights x room price
    total_rent     NUMBER(10, 2) NOT NULL,   -- subtotal + GST
    status         VARCHAR2(12) DEFAULT 'BOOKED' NOT NULL,
    user_id        NUMBER REFERENCES app_users(user_id),
    created_at     DATE DEFAULT SYSDATE,
    CONSTRAINT chk_res_dates  CHECK (check_out_date > check_in_date),
    CONSTRAINT chk_res_status CHECK (status IN ('BOOKED', 'CHECKED_OUT', 'CANCELLED'))
);

-- 3. Reserved rooms: links a reservation to its room.
CREATE TABLE reserved_rooms (
    reservation_id NUMBER NOT NULL,
    room_number    VARCHAR2(10) NOT NULL,
    PRIMARY KEY (reservation_id, room_number),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    FOREIGN KEY (room_number) REFERENCES rooms(room_number)
);

-- Standard rooms: single sharing, Rs 1500 / night
INSERT INTO rooms VALUES ('101', 'Standard', 1500.00, 1);
INSERT INTO rooms VALUES ('102', 'Standard', 1500.00, 1);
INSERT INTO rooms VALUES ('103', 'Standard', 1500.00, 1);
INSERT INTO rooms VALUES ('104', 'Standard', 1500.00, 1);
INSERT INTO rooms VALUES ('105', 'Standard', 1500.00, 1);

-- Deluxe rooms: double sharing, Rs 3500 / night
INSERT INTO rooms VALUES ('201', 'Deluxe', 3500.00, 2);
INSERT INTO rooms VALUES ('202', 'Deluxe', 3500.00, 2);
INSERT INTO rooms VALUES ('203', 'Deluxe', 3500.00, 2);
INSERT INTO rooms VALUES ('204', 'Deluxe', 3500.00, 2);
INSERT INTO rooms VALUES ('205', 'Deluxe', 3500.00, 2);

-- Suites: triple sharing, Rs 7500 / night
INSERT INTO rooms VALUES ('301', 'Suite', 7500.00, 3);
INSERT INTO rooms VALUES ('302', 'Suite', 7500.00, 3);
INSERT INTO rooms VALUES ('303', 'Suite', 7500.00, 3);
INSERT INTO rooms VALUES ('304', 'Suite', 7500.00, 3);
INSERT INTO rooms VALUES ('305', 'Suite', 7500.00, 3);

COMMIT;
