-- Drop existing tables to prevent conflicts if teammates re-run the script
DROP TABLE reserved_rooms CASCADE CONSTRAINTS;
DROP TABLE reservations CASCADE CONSTRAINTS;
DROP TABLE rooms CASCADE CONSTRAINTS;

-- 1. Rooms Table (Updated with INR pricing)
CREATE TABLE rooms (
    room_number VARCHAR2(10) PRIMARY KEY,
    room_type VARCHAR2(50) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    is_available NUMBER(1) DEFAULT 1 -- 1 for Available, 0 for Booked
);

-- Insert sample rooms in INR
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('101', 'Standard', 1500.00, 1);
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('102', 'Deluxe', 3500.00, 1);
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('103', 'Suite', 7500.00, 1);

-- 2. Reservations Header Table (Stores totals for the whole booking)
CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    contact_number VARCHAR2(15) NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    total_rent NUMBER(10, 2) NOT NULL
);

-- 3. Reserved Rooms Detail Table (Allows multiple rooms per reservation)
CREATE TABLE reserved_rooms (
    reservation_id NUMBER NOT NULL,
    room_number VARCHAR2(10) NOT NULL,
    PRIMARY KEY (reservation_id, room_number),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    FOREIGN KEY (room_number) REFERENCES rooms(room_number)
);

COMMIT;

-- Add the new column (defaults to 2 guests if not specified)
ALTER TABLE rooms ADD max_guests NUMBER(2) DEFAULT 2;

-- Set specific capacities for your current rooms
UPDATE rooms SET max_guests = 2 WHERE room_number = '101';
UPDATE rooms SET max_guests = 2 WHERE room_number = '102';
UPDATE rooms SET max_guests = 3 WHERE room_number = '103';

COMMIT;

-- Standard Rooms (Single Sharing - ₹1500.00)
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('104', 'Standard', 1500.00, 1, 1);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('105', 'Standard', 1500.00, 1, 1);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('106', 'Standard', 1500.00, 1, 1);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('107', 'Standard', 1500.00, 1, 1);

-- Deluxe Rooms (Double Sharing - ₹3500.00)
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('201', 'Deluxe', 3500.00, 1, 2);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('202', 'Deluxe', 3500.00, 1, 2);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('203', 'Deluxe', 3500.00, 1, 2);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('204', 'Deluxe', 3500.00, 1, 2);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('205', 'Deluxe', 3500.00, 1, 2);

-- Suite Rooms (Triple Sharing - ₹7500.00)
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('301', 'Suite', 7500.00, 1, 3);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('302', 'Suite', 7500.00, 1, 3);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('303', 'Suite', 7500.00, 1, 3);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('304', 'Suite', 7500.00, 1, 3);
INSERT INTO rooms (room_number, room_type, price, is_available, max_guests) VALUES ('305', 'Suite', 7500.00, 1, 3);

COMMIT;