-- Run database_setup.sql instead for a fresh database.
-- Upgrade an older HotelReservationSystem database without deleting reservations.
-- Run this as the same Oracle user configured in db.properties.

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE reservations ADD (status VARCHAR2(12) DEFAULT ''BOOKED'' NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE app_users (
        user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(30) UNIQUE NOT NULL,
        password_hash VARCHAR2(64) NOT NULL,
        salt VARCHAR2(32) NOT NULL,
        full_name VARCHAR2(100) NOT NULL,
        phone VARCHAR2(15) NOT NULL,
        email VARCHAR2(100),
        role VARCHAR2(10) NOT NULL CHECK (role IN (''ADMIN'', ''CUSTOMER'')),
        created_at DATE DEFAULT SYSDATE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE reservations ADD (user_id NUMBER REFERENCES app_users(user_id))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE reservations ADD (created_at DATE DEFAULT SYSDATE)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE reservations ADD CONSTRAINT chk_res_status CHECK (status IN (''BOOKED'', ''CHECKED_OUT'', ''CANCELLED''))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE rooms ADD (max_guests NUMBER(2) DEFAULT 2)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE reservations
SET status = 'BOOKED'
WHERE status IS NULL;

COMMIT;
