-- Drop existing tables to prevent conflicts if teammates re-run the script
DROP TABLE reserved_rooms CASCADE CONSTRAINTS;
DROP TABLE reservations CASCADE CONSTRAINTS;
DROP TABLE rooms CASCADE CONSTRAINTS;

-- 1. Rooms Table (Updated with INR pricing)
CREATE TABLE rooms (
    room_number VARCHAR2(10) PRIMARY KEY,
    room_type VARCHAR2(50) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    is_available NUMBER(1) DEFAULT 1 -- 1 for Available, 0 for Booked
);

-- Insert sample rooms in INR
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('101', 'Standard', 1500.00, 1);
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('102', 'Deluxe', 3500.00, 1);
INSERT INTO rooms (room_number, room_type, price, is_available) VALUES ('103', 'Suite', 7500.00, 1);

-- 2. Reservations Header Table (Stores totals for the whole booking)
CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    contact_number VARCHAR2(15) NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    total_rent NUMBER(10, 2) NOT NULL
);

-- 3. Reserved Rooms Detail Table (Allows multiple rooms per reservation)
CREATE TABLE reserved_rooms (
    reservation_id NUMBER NOT NULL,
    room_number VARCHAR2(10) NOT NULL,
    PRIMARY KEY (reservation_id, room_number),
    FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id) ON DELETE CASCADE,
    FOREIGN KEY (room_number) REFERENCES rooms(room_number)
);

COMMIT;